### ISSUE TITLE
There are some problems with this website：https://evitsam.hanlab.ai/

### ISSUE THREAD

**Issue by LHX1220328779** [mit-han-lab/efficientvit#119]

**Comment by han-cai** [comment]
Thank you for informing us of the problem. We have fixed the issue.

**Comment by eyaler** [comment]
@han-cai it's down again

**Comment by han-cai** [comment]
Hi eyaler,

We have fixed the issue. It works on my side now. Let me know if the problem still exists on your side. 

Best,
Han

**Comment by eyaler** [comment]
@han-cai sorry not working for me - i get a cloudflare server down error

**Comment by han-cai** [comment]
@eyaler, I checked with my friends. All of them can visit the website and run the demo. The issue seems to come from your side.
