### ISSUE TITLE
EfficientViT b0 pretrained in ImageNet

### ISSUE THREAD

**Issue by seefun** [mit-han-lab/efficientvit#14]
Have you tested EfficientViT-b0 on ImageNet? And could you share the pretrained weights of EfficientViT-b0 in ImageNet 1k?

**Comment by han-cai** [comment]
Hi seefun,

You can download the pretrained weight of EfficientViT-B0 using the following link:

https://drive.google.com/file/d/1ganFBZmmvCTpgUwiLb8ePD6NBNxRyZDk/view?usp=drive_link

**Comment by seefun** [comment]
@han-cai  Efficientvit series has been added into TIMM as EfficientViT (MIT) 
https://github.com/huggingface/pytorch-image-models
