### ISSUE TITLE
Questions about DC-AE

### ISSUE THREAD

**Issue by theFoxofSky** [mit-han-lab/efficientvit#141]
Q1. The design of the Residual Autoencoding Downsample block is very strange, which is equivalent to a 1x2 average pooling and a 2x1 pixel unshuffle. See below.

![image](https://github.com/user-attachments/assets/37049e58-d7b0-4f84-bdba-46659f639575)

It is equivalent to first doing 1x2 average pooling to get 1+3 and 2+4, then doing a 2x1 pixel unshuffle. Why design like this? Will this non-square average pooling cause strange artifacts?

Q2. I think the comparison in Table 2 about PSNR and rFID is unfair and not convincing. 

Given a standard SDXL VAE with f8c4, we can easily transfer it to the f32c64 or f64c256 VAE by applying pixel unshuffle and pixel shuffle to its latent, which is **TRAINING FREE**,  without information loss, and with higher PSNR than corresponding DC-AE. 

Q3. The above modification of SDXL VAE is mathematically equivalent to enlarging the patch size of DiT. However, in Table 4, why does SD-VAE-f8 with p4 get worse FID than DC-AE-f32 p1? 

I mean SD-VAE-f8 with 4x pixel unshuffle/shuffle on latent should get a higher PSNR than DC-AE-f32. Why did it get much worse FID in diffusion model training?

Similarly, the most confusing part of the whole paper is in Table 3.

As we all know, Flux-VAE-f8 is a very good VAE with a super high PSNR. However, in Table 3, the diffusion model trained on Flux-VAE-f8 is 2 times worse in FID  (w/o cfg) than the one trained on SD-VAE-f8, and 4 times worse in FID (w/ cfg) than the one trained on SD-VAE-f8. **WHY?**

**Comment by cnsdqd-dyb** [comment]
I have similar doubts. In fact, when I saw that DC-AE increased the number of channels several times, I realized that its compression ratio remained the same, and it compresses 2x more than SD VAE overall. However, the experiments in Table 2 show that the PSNR of SD VAE is extremely poor. According to my understanding, using pixel shuffle can achieve a spatial to channel conversion losslessly and training-free, actually without any loss. Given that SD VAE compresses twice as much overall, I estimate that the PSNR might decrease by at most 3 points (if anyone has SD VAE 1x8x8 ch=4 PSNR evaluation metrics on a related dataset, please list them). Overall, such a comparison might lose its persuasive power.

**Comment by francois-rozet** [comment]
I had some similar questions.

> I mean SD-VAE-f8 with 4x pixel unshuffle/shuffle on latent should get a higher PSNR than DC-AE-f32. Why did it get much worse FID in diffusion model training?

My intuition is that because the deepest blocks of the DC-AE are (efficient) ViT blocks, the latent representation is already well suited for a transformer. Comparatively, the latent representation of SD-VAE-f8 or Flux-VAE-f8, are well suited for CNNs. Using a pixel unshuffle/patchify, does not make this representation transformer-friendly. This could explain the gap.

**Comment by han-cai** [comment]
Thanks for your interest in our work and for raising the questions. Let me clarify below:

## DC-AE-Diffusion
> Q3. The above modification of SDXL VAE is mathematically equivalent to enlarging the patch size of DiT. However, in Table 4, why does SD-VAE-f8 with p4 get worse FID than DC-AE-f32 p1?

> As we all know, Flux-VAE-f8 is a very good VAE with a super high PSNR. However, in Table 3, the diffusion model trained on Flux-VAE-f8 is 2 times worse in FID (w/o cfg) than the one trained on SD-VAE-f8, and 4 times worse in FID (w/ cfg) than the one trained on SD-VAE-f8. WHY?

For latent diffusion models, better autoencoder reconstruction performance does not necessarily translate to better diffusion generation performance. For example, we can directly use a space-to-channel operation (PixelUnshuffle) to encode the raw image to the latent with shape (H/p, W/p), and losslessly decode the latent to the original image using a channel-to-space operation (PixelShuffle). This autoencoder has the best reconstruction performance, but we will get poor diffusion generation performance using this autoencoder. 

As discussed in Section 3.3 of [DC-AE](https://arxiv.org/abs/2410.10733), this design is equivalent to applying a diffusion transformer with patch size p to the raw image space. It is a fake token compression, leaving the token compression task to the diffusion transformer. **In this design, the diffusion transformer has to learn denoising and token compression simultaneously.** 

In our work, we find training DC-AE to achieve the target token compression ratio can achieve much better diffusion generation performance than combining a low spatial-compression autoencoder with the space-to-channel operation (PixelUnshuffle) (Figure 2b of [DC-AE](https://arxiv.org/abs/2410.10733)). **In this design, DC-AE takes over the whole token compression task and the diffusion model can fully focus on the denoising task.** That's the core difference between DC-AE and SD-VAE-f8+PixelUnshuffle or Flux-VAE-f8+PixelUnshuffle, leading to the improvements.
 
We have added guides about training diffusion transformers with [SD-VAE-f8](https://github.com/mit-han-lab/efficientvit/blob/master/assets/train_diffusion_with_sd_vae_f8.md) and [Flux-VAE-f8](https://github.com/mit-han-lab/efficientvit/blob/master/assets/train_diffusion_with_flux_vae_f8.md). There are also open-source repos supporting training diffusion transformers with SD-VAE-f8:
- https://github.com/chuanyangjin/fast-DiT
- https://github.com/baofff/U-ViT

## DC-AE

> I had similar questions.
> 
> My intuition is that because the deepest blocks of the DC-AE are (efficient) ViT blocks, the latent representation is already well suited for a transformer. Comparatively, the latent representation of SD-VAE-f8 or Flux-VAE-f8, are well suited for CNNs. Using a pixel unshuffle/patchify, does not make this representation transformer-friendly. This could explain the gap.

The deepest blocks of SD-VAE-f8 and Flux-VAE-f8 are also ViT blocks. 

> Q2. I think the comparison in Table 2 about PSNR and rFID is unfair and not convincing.

> I have similar doubts. In fact, when I saw that DC-AE increased the number of channels several times, I realized that its compression ratio remained the same, and it compresses 2x more than SD VAE overall. However, the experiments in Table 2 show that the PSNR of SD VAE is extremely poor. According to my understanding, using pixel shuffle can achieve a spatial to channel conversion losslessly and training-free, actually without any loss. Given that SD VAE compresses twice as much overall, I estimate that the PSNR might decrease by at most 3 points (if anyone has SD VAE 1x8x8 ch=4 PSNR evaluation metrics on a related dataset, please list them). Overall, such a comparison might lose its persuasive power.

Table 2 is an apple-to-apple comparison between DC-AE and SD-VAE under the same autoencoder settings. f32/f64/f128 and f8+p4/f8+p8/f8+p16 are different autoencoder settings, and they have significantly different behaviors when applied to latent diffusion models.  

> Q1. The design of the Residual Autoencoding Downsample block is very strange, which is equivalent to a 1x2 average pooling and a 2x1 pixel unshuffle. See below.

> It is equivalent to first doing 1x2 average pooling to get 1+3 and 2+4, then doing a 2x1 pixel unshuffle. Why design like this? Will this non-square average pooling cause strange artifacts?

The core goal of this design is to alleviate the optimization difficulty of high spatial-compression autoencoders (Section 3.1 and 3.2 of [DC-AE](https://arxiv.org/abs/2410.10733)). In practice, this design works well and does not suffer from any artifacts. We have released our models and provided the [guide](https://github.com/mit-han-lab/efficientvit/tree/master/applications/dc_ae#deep-compression-autoencoder) on how to use our models. You're welcome to try our DC-AE models.

**Comment by francois-rozet** [comment]
If I am not mistaken, there is a single attention layer in SD and Flux VAEs. In addition this attention layer has a single head, and is performed at 64x64 resolution. This is vastly different from the (efficient) ViT blocks in your work.

https://github.com/black-forest-labs/flux/blob/main/src/flux/modules/autoencoder.py
