### ISSUE TITLE
What does in/mix mean?

### ISSUE THREAD

**Issue by Godofnothing** [mit-han-lab/efficientvit#144]
Thanks for your great work!

On the [HF model card](https://huggingface.co/collections/mit-han-lab/dc-ae-670085b9400ad7197bb1009b) there are models with `in` and `mix` suffixes, for example `mit-han-lab/dc-ae-f32c32-in-1.0`. 

What do these suffixes actually mean? Is one option expected to be better than the other, or does it depend on the specific use case?

**Comment by han-cai** [comment]
`in` means the models are trained with ImageNet only. `mix` means the models are trained with a mixture of datasets (Section 4.1). We do not find one option strictly outperforms or underperforms the other. I suggest choosing the one that gives the best performance for your target use case.

**Comment by Godofnothing** [comment]
@han-cai Thanks for yor reply and clarification!

**Comment by DongfeiJi** [comment]
dear，what the sana mean？

**Comment by DongfeiJi** [comment]
i mean mit-han-lab/dc-ae-f32c32-sana-1.0，what is this model

**Comment by han-cai** [comment]
It refers to the DC-AE model used in [SANA](https://nvlabs.github.io/Sana/).
