### ISSUE TITLE
是否可以直接替换stable diffusion的vae使用

### ISSUE THREAD

**Issue by catsled** [mit-han-lab/efficientvit#145]
如题，想要训练分辨率更高的图像，但是显存受限

**Comment by han-cai** [comment]
Hi @catsled,

You can replace SD-VAE-f8 with DC-AE to reduce the training memory cost without changing the diffusion model architecture. We have detailed comparisons in Tables 3, 4, and 5 of the [paper](https://arxiv.org/abs/2410.10733). 

Best,
Han

**Comment by CuddleSabe** [comment]
> Hi [@catsled](https://github.com/catsled),
> 
> You can replace SD-VAE-f8 with DC-AE to reduce the training memory cost without changing the diffusion model architecture. We have detailed comparisons in Tables 3, 4, and 5 of the [paper](https://arxiv.org/abs/2410.10733).
> 
> Best, Han

Hi, I found that I can replace DiT-base's vae easily by training , but I can't replace the vae in unet. the effects is weird
