### ISSUE TITLE
DC-AE is much worse than sd-vae-ft-ema

### ISSUE THREAD

**Issue by eisneim** [mit-han-lab/efficientvit#149]
the gif of this project shows DC-AE is reconstruct  better results, but in my test, is much worse
![1721560201888_78](https://github.com/user-attachments/assets/0115b81d-5821-40fc-b3b5-4bec4eb773f3)

![截图 2024-11-03 11-26-42](https://github.com/user-attachments/assets/d1bef5a7-6851-4ff4-92da-ddb7dd107b29)
## DC-AE
i have tried some of release weights, they all performed very bad
```
# link = "mit-han-lab/dc-ae-f32c32-sana-1.0"
# link = "mit-han-lab/dc-ae-f32c32-in-1.0"
link = "mit-han-lab/dc-ae-f64c128-in-1.0"
dc_ae = DCAE_HF.from_pretrained(link)
```
![截图 2024-11-03 11-27-17](https://github.com/user-attachments/assets/c520825a-4e27-4541-9399-a194c726e068)

## compression ratio: 
DC-AE latent shape: 128 * 8 * 8
SD-VAE latent shape: 4 * 64 * 64
(4 * 64 * 64 ) / (128 * 8 * 8) = 2 just 2x more compression but much worse quality, what's the point?
or am i miss something??

**Comment by han-cai** [comment]
Thanks for your interest in our work.

1. The reconstruction quality gif compares DC-AE and SD-VAE using the same autoencoder setting (64x64 compression). In your test, the comparison is under different settings. 

2. Improving the reconstruction quality of small human faces is one aspect we seek to improve in our next release. Please stay tuned.
