### ISSUE TITLE
Question about training command in DC-VAE README

### ISSUE THREAD

**Issue by Sy-Zhang** [mit-han-lab/efficientvit#150]
Hi there! Congrats for the great work! I have a question regarding this training [command]( https://github.com/mit-han-lab/efficientvit/blob/master/applications/dc_ae/README.md?plain=1#L188-L198) in DC-VAE README. After training, is it supposed to get similar FID shown in the second to last row in Table 3?

**Comment by han-cai** [comment]
Yes. The expected results of UViT-h+DC-AE-f64 are around FID 13.96 (12.26) without CFG and FID 3.01 (2.66) with CFG=1.5 after training for 500k (2,000k) steps using the given command.
