### ISSUE TITLE
Why is it named DC AE not DC VAE

### ISSUE THREAD

**Issue by TheSeriousProgrammer** [mit-han-lab/efficientvit#155]
Phenomenal achievement of SANA and DC AE kudos(big fan have been following you guys since the tinyml hanlab courses)

But I just have one doubt, why is the system named DC AE and not DC VAE

Does it mean that it's trained as a autoencoder and not variational autoencoder? If that's the case how is diffusion working with it?

Asking because the latent space of a VAE is guaranteed to be reliable and continuous through out which allows for diffusion systems to make incremental changes, but the same is not true with vanilla autoencoders right?

**Comment by han-cai** [comment]
Thanks for the question. 

You are right. We trained DC-AE models as autoencoders instead of variational autoencoders. We found that autoencoders and variational autoencoders perform similarly in our experiments, so we chose the simpler one. The model seems to still learn a good latent space without explicit supervision, allowing diffusion models to make incremental changes.

**Comment by TheSeriousProgrammer** [comment]
Was it done to reduce the training computation cost?

**Comment by chenjy2003** [comment]
No. I think the computation cost of KL loss can be negligible. We just want to remove the unnecessary components from our models.

**Comment by fzimmermann89** [comment]
Just to clarify: you did not use any regularitzation on the latent space during training, only a scaling factor afterwards?

**Comment by chenjy2003** [comment]
@fzimmermann89 Correct, we did not regularize the latent space during training.

**Comment by TheSeriousProgrammer** [comment]
oh.. so if latenct space was not regularized and if no KL loss too was involved how was the problem of over shooting values got fixed? Generally if the latent space is not normalized/regularized then there will be no constraints in it right? would'nt it then potentially result in a sparsely used latent space

**Comment by chenjy2003** [comment]
@TheSeriousProgrammer In practice, we didn't observe such an issue when training latent diffusion models. We found that autoencoders and variational autoencoders perform the same.

**Comment by cai525** [comment]
Thank you for your excellent work.  I also have the same question as @TheSeriousProgrammer. Latent Diffusion Models (e.g., LDM) typically use a VAE to obtain the latent representation, based on the belief that VAEs provide a continuous and regularized latent space — something that plain AEs are thought to lack. However, the experimental results of DC-AE seem to challenge this conventional view. What is your perspective or explanation for this phenomenon?
