### ISSUE TITLE
missing 1 required positional argument "model_name'

### ISSUE THREAD

**Issue by MrProSe** [mit-han-lab/efficientvit#162]
![image](https://github.com/user-attachments/assets/656a808d-4098-4741-98cf-37af29d382df)

**Comment by chenjy2003** [comment]
Hi, could you please provide the command you are using?

**Comment by MrProSe** [comment]
![QQ截图20241211201723](https://github.com/user-attachments/assets/a3d6e3ed-70c7-4151-8274-c0016de7c8e0)
I use this code, name it as test_dcae.py, and then use the command" run test_dcae.py"

**Comment by chenjy2003** [comment]
It is kind of strange that the error is related to `DCAE_Diffusion_HF` which doesn't exist in this code. Could you please also share the complete error message? Thanks!

**Comment by MrProSe** [comment]
Sorry, I may have made a mistake. Because I always run it in the laboratory. Now there is something wrong with the laboratory. I will provide you with the error information after it recovers.

**Comment by MrProSe** [comment]
I use this code, name it as test_dcae.py, and then use the command" python test_dcae.py"
![image](https://github.com/user-attachments/assets/bf3657b2-1fb9-4efa-bdc9-e0d92254d876)
But error happens：
![image](https://github.com/user-attachments/assets/52c686e5-2da6-4150-a860-4c1d00a167eb)

**Comment by chenjy2003** [comment]
Thanks for providing the information. To locate the issue, could you please further try the following:

- Try to see if other models have the same issue. For example, replace `dc-ae-f64c128-in-1.0` with `dc-ae-f32c32-in-1.0`.
- Under this folder `~/.cache/huggingface/hub/models--mit-han-lab--dc-ae-f64c128-in-1.0/snapshots/`, there will be some directories containing the configurations and weights. Could you please share the content of the `config.json`? For example, I got this output:
```
cat ~/.cache/huggingface/hub/models--mit-han-lab--dc-ae-f64c128-in-1.0/snapshots/af215f97817822c578523addb32e9f0c2827b223/config.json
{
  "model_name": "dc-ae-f64c128-in-1.0"
}
```

**Comment by MrProSe** [comment]
It seems to report this error right before downloading the model, because in the directory ~/.cache/huggingface/hub/ I don't have the folder models--mit-han-lab--dc-ae-f64c128-in-1.0/snapshots
![image](https://github.com/user-attachments/assets/d69954ff-7846-4147-b82c-74e6ad176ccd)

**Comment by chenjy2003** [comment]
The autoencoders are supposed to be downloaded automatically when you run `DCAE_HF.from_pretrained("mit-han-lab/dc-ae-f64c128-in-1.0")`. Which version of `pip show huggingface-hub` are you using?

**Comment by MrProSe** [comment]
0.26.3
![image](https://github.com/user-attachments/assets/fd711852-6ebf-42bb-8b03-c99e8cbd878a)

**Comment by chenjy2003** [comment]
I tried this version and the behavior is normal. When you run the script for the first time, did you see a downloading progress bar like this?
![image](https://github.com/user-attachments/assets/d03de454-682b-4c20-8847-02507a429c15)

**Comment by MrProSe** [comment]
No, I only got the above mentioned error on my first try

**Comment by chenjy2003** [comment]
Maybe there is something wrong with huggingface... Can you manually download the checkpoint using this command `git clone https://huggingface.co/mit-han-lab/dc-ae-f64c128-in-1.0`?
<img width="681" alt="image" src="https://github.com/user-attachments/assets/f85b169e-0c82-4c00-b41c-78b66634d420" />

**Comment by chenjy2003** [comment]
You need to change `mit-han-lab/dc-ae-f64c128-in-1.0` to the path of the downloaded checkpoint, like `/home/junyuc/workspace/tmp/dc-ae-f64c128-in-1.0`

**Comment by MrProSe** [comment]
Well it's solved now, thanks for your help.By the way,I want to port dcae to other models, how should I do that?

**Comment by chenjy2003** [comment]
You are welcome. What do you mean by "port dcae to other models"?

**Comment by MrProSe** [comment]
For example, I want to change the autoencoder in SD to dcae to see if it improves, how should I do that?

**Comment by chenjy2003** [comment]
Do you mean developing latent diffusion models using DCAE as the autoencoder instead of SDVAE?

If so, you need to train diffusion models on the latent space of DCAE, and you can follow the examples [here](https://github.com/mit-han-lab/efficientvit/blob/20317cb7240c81e9ded74501a523846597021133/applications/dc_ae/README.md?plain=1#L87).
