### ISSUE TITLE
Where should I download the dataset

### ISSUE THREAD

**Issue by BolunDai0216** [mit-han-lab/efficientvit#19]
Hi,

Thanks for open-sourcing this great work!

I was wondering when running your evaluation code if/where I should download the datasets? If you can provide the relative path w.r.t. the repo root directory that would be great!

Thanks in advance!

**Comment by han-cai** [comment]
Hi Bolun,

I have updated the README, adding descriptions about the expected dataset directory structure. Let me know if you still have problems with this.

Best,
Han
