### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by Yonghao-Tan** [mit-han-lab/efficientvit#2]
Hello, the efficientvit model you provided is impressive. I want to study it in depth and modify it to learn better. But I am missing the training code. Could you provide the training code for this code, please?

**Comment by arnvsnigi** [comment]
Yeah....Even i am trying to study and research this impressive code.Could you please provide us with it.It would be really helpful for us and enable us to do higher research.

**Comment by han-cai** [comment]
The training guide for ImageNet classification is available at https://github.com/mit-han-lab/efficientvit/blob/master/TRAINING.md.

The training guide for segmentation will be released soon.

Thanks for your interest in our work.

**Comment by Yonghao-Tan** [comment]
Thank you very much for releasing new training ocde. It will be great for our research study.



---Original---
From: "Han ***@***.***&gt;
Date: Fri, Jul 21, 2023 23:13 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mit-han-lab/efficientvit] About training (Issue #2)




 
The training guide for ImageNet classification is available at https://github.com/mit-han-lab/efficientvit/blob/master/TRAINING.md.
 
The training guide for segmentation will be released soon.
 
Thanks for your interest in our work.
