### ISSUE TITLE
Tensorflow Lite models

### ISSUE THREAD

**Issue by gaetanbahl** [mit-han-lab/efficientvit#3]
Hello, thanks for this work.

Could you share the Tensorflow lite models that were used for benchmarking? Or even better, could you also share the code to convert from PyTorch to TFLite? I would like to try quantizing the models.

Thanks in advance.

**Comment by han-cai** [comment]
Hi,

I have added the code for converting Pytorch models to TFLite models: 
https://github.com/mit-han-lab/efficientvit/blob/master/export_tflite.py

I will close this issue for now. Feel free to contact me if you have any further questions.  

Best regards,
Han
