### ISSUE TITLE
 Segmentation training code

### ISSUE THREAD

**Issue by d710055071** [mit-han-lab/efficientvit#35]
I cannot reproduce the semantic segmentation results. When can I open up the training code for semantic segmentation? Thank you very much

**Comment by d710055071** [comment]
+---------------+-------+-------+--------+-----------+--------+-------+
|     Class     |  IoU  |  Acc  | Fscore | Precision | Recall |  Dice |
+---------------+-------+-------+--------+-----------+--------+-------+
|      road     |  0.0  |  0.0  |  nan   |    nan    |  0.0   |  0.0  |
|    sidewalk   | 23.59 | 93.33 | 38.18  |    24.0   | 93.33  | 38.18 |
|    building   | 62.84 | 78.81 | 77.18  |   75.62   | 78.81  | 77.18 |
|      wall     | 21.46 | 23.71 | 35.34  |   69.35   | 23.71  | 35.34 |
|     fence     |  2.27 |  2.43 |  4.45  |   25.82   |  2.43  |  4.45 |
|      pole     |  1.34 |  1.39 |  2.65  |   29.64   |  1.39  |  2.65 |
| traffic light |  3.95 | 29.46 |  7.6   |    4.37   | 29.46  |  7.6  |
|  traffic sign | 88.65 | 95.64 | 93.98  |   92.38   | 95.64  | 93.98 |
|   vegetation  | 57.61 | 79.86 |  73.1  |    67.4   | 79.86  |  73.1 |
|    terrain    | 21.44 | 28.63 | 35.31  |   46.07   | 28.63  | 35.31 |
|      sky      |  0.0  |  0.0  |  nan   |    0.0    |  0.0   |  0.0  |
|     person    | 72.05 | 95.72 | 83.76  |   74.45   | 95.72  | 83.76 |
|     rider     | 18.65 | 21.77 | 31.44  |   56.57   | 21.77  | 31.44 |
|      car      | 18.36 | 26.03 | 31.02  |   38.39   | 26.03  | 31.02 |
|     truck     | 29.98 | 30.31 | 46.13  |   96.51   | 30.31  | 46.13 |
|      bus      | 31.49 | 53.16 |  47.9  |   43.58   | 53.16  |  47.9 |
|     train     |  nan  |  nan  |  nan   |    nan    |  nan   |  nan  |
|   motorcycle  | 27.58 | 36.57 | 43.24  |   52.88   | 36.57  | 43.24 |
|    bicycle    |  0.0  |  0.0  |  nan   |    0.0    |  0.0   |  0.0  |
+---------------+-------+-------+--------+-----------+--------+-------+
2023-09-30 11:13:01,991 - mmseg - INFO - Summary:
2023-09-30 11:13:01,991 - mmseg - INFO - 
+-------+-------+-------+---------+------------+---------+-------+
|  aAcc |  mIoU |  mAcc | mFscore | mPrecision | mRecall | mDice |
+-------+-------+-------+---------+------------+---------+-------+
| 85.45 | 26.74 | 38.71 |  43.42  |   46.88    |  38.71  | 36.18 |
+-------+-------+-------+---------+------------+---------+-------+
2023-09-30 11:13:01,994 - mmseg - INFO - The previous best checkpoint /data2/dongzf/workdir/efficentvit_cityspace_v1/best_mIoU_epoch_693.pth was removed
2023-09-30 11:13:02,067 - mmseg - INFO - Now best checkpoint is saved as best_mIoU_epoch_697.pth.
2023-09-30 11:13:02,067 - mmseg - INFO - Best mIoU is 0.2674 at 697 epoch.

**Comment by mzahana** [comment]
@d710055071 Is there a code to train the semantic segmentation on custom dataset?
