### ISSUE TITLE
EfficientVit-B0 ImageNet Weights

### ISSUE THREAD

**Issue by MarkWijkhuizen** [mit-han-lab/efficientvit#9]
Would it be possible to provide the weights of the EfficientVit-B0 model trained on ImageNet.

**Comment by han-cai** [comment]
You can download the weight using the following link:
https://drive.google.com/file/d/1ganFBZmmvCTpgUwiLb8ePD6NBNxRyZDk/view?usp=sharing

**Comment by MarkWijkhuizen** [comment]
Many thanks for sharing the weights!
