### ISSUE TITLE
what's the version of tensorrt?

### ISSUE THREAD

**Issue by freeman745** [mit-han-lab/efficientvit#96]
What's the version of tensorrt?

**Comment by Anivie** [comment]
See [here](https://github.com/mit-han-lab/efficientvit/blob/8e87f05d321c9dc941c816f093cedcbcb3eb4234/deployment/sam/onnx/export_decoder.py#L148), default is 17 and you can use any older then 11.

**Comment by zhuoyang20** [comment]
Hi @freeman745,

We use TensorRT-8.6.1.6.

Best,
Zhuoyang

**Comment by freeman745** [comment]
Thanks for your reply!
